---

- name: Airflow | Check Admin user (> 2.0)
  command: "{{ airflow_executable }} users list"
  register: airflow_check_admin
  changed_when: false
  when: airflow_version is version( '2.0.0', '>=')

- name: Airflow | Create Admin user AUTH_DB (> 2.0)
  command:
    argv:
      - "{{ airflow_executable }}"
      - users
      - create
      - --username
      - "{{ item.username }}"
      - --password
      - "{{ item.password }}"
      - --firstname
      - "{{ item.firstname }}"
      - --lastname
      - "{{ item.lastname }}"
      - --role
      - "{{ item.role }}"
      - --email
      - "{{ item.email }}"
  with_items: "{{ airflow_admin_users }}"
  when:
    - airflow_version is version( '2.0.0', '>=')
    - "item.email not in airflow_check_admin.stdout"
    - "airflow_AUTH_TYPE == 'AUTH_DB'"

- name: Airflow | Create Admin users AUTH_LDAP (> 2.0)
  command:
    argv:
      - "{{ airflow_executable }}"
      - users
      - create
      - --username
      - "{{ item.username }}"
      - --password
      - "{{ item.password }}"
      - --firstname
      - "{{ item.firstname }}"
      - --lastname
      - "{{ item.lastname }}"
      - --role
      - "{{ item.role }}"
      - --email
      - "{{ item.email }}"
  with_items: "{{ airflow_admin_users }}"
  when:
    - airflow_version is version( '2.0.0', '>=')
    - "item.email not in airflow_check_admin.stdout"
    - "airflow_AUTH_TYPE == 'AUTH_LDAP'"
